imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

braincrafted_bootstrap:
    auto_configure:
        assetic: false
        twig: true
        knp_menu: false
        knp_paginator: false

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

mop_arango_db:
    default_connection: main # optional will be set to the first connection if not present
    connections:
        main:
            host: 127.0.0.1
            port: 8529
    fos:
        connection: main
        collection: users

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: custom
    user_class: Acme\DemoBundle\Entity\User
    firewall_name: main
    service:
        user_manager: mop_arangodb.fos.user_manager
